### ISSUE TITLE
Automatic dive calculations class.

### ISSUE THREAD

**Issue by arjo129** [CS2113-AY1819S1-W13-2/main#17]
Write a class that takes number of minutes spent under water and initial PG and converts it to final PG.

**Comment by cjunxiang** [comment]
take note of my latest PR, has new compareUtil class with functions that compares 2 time and gives you the difference in number of minutes. 
work with a imaginary variable Difference that my method returns for now....
soon this Variable "difference" will be accurate and compares date+time difference instead of just time.

**Comment by shuanang** [comment]
done in the latest merge #47. Will deal with compareUtil class in upcoming milestone!
